In [1]:
print("Mu name is abid")

Mu name is abid


In [2]:
age = 12

if age > 20 :
    print('OLDDD')
else :
    print("Not Old")

Not Old


In [3]:
age = 12

if age > 20 :
    print('OLDDD')
else :
    print("Not Old")

Not Old


In [4]:
age = 12

if age > 20 :
    print('OLDDD')
else :
    print("Not Old")

Not Old


In [5]:
12


print("nama saya Muhasmadmas")

nama saya Muhasmadmas


In [6]:
age = 12

if age > 20 :
    print('OLDDD')
else :
    print("Not Old")

Not Old


In [11]:
class Person():

    def __init__(self, nama, umur, gender):
        self.nama = nama
        self.umur = umur
        self.gender = gender

    def menyapa_oranglain(self):
        print("Halo dari saya : ", self.nama)

In [12]:
orangkesatu = Person("Ezzar", 12, "Laki-laki")
orangkedua = Person("Elang", 11, "Laki-laki")
orangketiga = Person("Sutri", 14, "Perempuan")

In [6]:
print(orangkesatu.nama)
print(orangkedua.nama)
print(orangketiga.nama)

Ezzar
Elang
Sutri


In [7]:
print(orangkesatu.umur)
print(orangkedua.umur)
print(orangketiga.umur)

12
11
14


In [8]:
print(orangkesatu.gender)
print(orangkedua.gender)
print(orangketiga.gender)

Laki-laki
Laki-laki
Perempuan


In [14]:
orangkesatu.menyapa_oranglain()
orangkedua.menyapa_oranglain()
orangketiga.menyapa_oranglain()

Halo dari saya :  Ezzar
Halo dari saya :  Elang
Halo dari saya :  Sutri


In [3]:
class animal:
    def __init__(self, nama, gerak):
        self.nama = nama
        self.jalan = gerak



animalkesatu = animal("simaung", "lari")
animalkedua = animal("rajahutan", "lari")

In [4]:
class Harimau(animal):
    def __init__(self, nama, gerak):
        super().__init__(nama, gerak)


harimaukesatu = Harimau("bangjago", 'lari')


In [5]:
import numpy as np

mylist = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(type(mylist))

arraysaya = np.array(mylist)
print(type(arraysaya))



<class 'list'>
<class 'numpy.ndarray'>


In [9]:
print(arraysaya + 2)
print(arraysaya - 2)
print(arraysaya * 2)
print(arraysaya / 2)


[ 3  4  5  6  7  8  9 10 11 12]
[-1  0  1  2  3  4  5  6  7  8]
[ 2  4  6  8 10 12 14 16 18 20]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(1, 100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [24]:
np.arange(900,1000)

array([900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912,
       913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925,
       926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938,
       939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951,
       952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964,
       965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977,
       978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990,
       991, 992, 993, 994, 995, 996, 997, 998, 999])

In [27]:
np.linspace(1,10, num = 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [29]:
np.linspace(1, 100, num= 200)

array([  1.        ,   1.49748744,   1.99497487,   2.49246231,
         2.98994975,   3.48743719,   3.98492462,   4.48241206,
         4.9798995 ,   5.47738693,   5.97487437,   6.47236181,
         6.96984925,   7.46733668,   7.96482412,   8.46231156,
         8.95979899,   9.45728643,   9.95477387,  10.45226131,
        10.94974874,  11.44723618,  11.94472362,  12.44221106,
        12.93969849,  13.43718593,  13.93467337,  14.4321608 ,
        14.92964824,  15.42713568,  15.92462312,  16.42211055,
        16.91959799,  17.41708543,  17.91457286,  18.4120603 ,
        18.90954774,  19.40703518,  19.90452261,  20.40201005,
        20.89949749,  21.39698492,  21.89447236,  22.3919598 ,
        22.88944724,  23.38693467,  23.88442211,  24.38190955,
        24.87939698,  25.37688442,  25.87437186,  26.3718593 ,
        26.86934673,  27.36683417,  27.86432161,  28.36180905,
        28.85929648,  29.35678392,  29.85427136,  30.35175879,
        30.84924623,  31.34673367,  31.84422111,  32.34

In [34]:
print(arraysaya[6])
print(arraysaya[7])
print(arraysaya[8])

7
8
9


In [8]:
import numpy as np
# NUMPY ARRAY
#ACCESSING ELEMENT

arraysaya = np.array([ 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(arraysaya[0])
print(arraysaya[1])
print(arraysaya[2])
print(arraysaya[3])
print(arraysaya[4])

11
12
13
14
15


In [16]:
arraysaya2 = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

print(arraysaya2[0])
print(arraysaya2[1])
print(arraysaya2[2])


print(arraysaya2[0][1])
print(arraysaya2[1][1])
print(arraysaya2[2][1])


[1 2 3]
[4 5 6]
[7 8 9]
2
5
8


In [32]:
np.random.randint(1, 5, size = 100)

array([3, 2, 1, 2, 3, 3, 3, 3, 3, 1, 4, 3, 4, 2, 2, 1, 4, 4, 1, 4, 2, 1,
       2, 3, 4, 1, 2, 4, 2, 1, 2, 1, 4, 4, 2, 1, 2, 4, 2, 1, 4, 1, 3, 3,
       3, 3, 2, 2, 4, 4, 2, 2, 2, 3, 2, 1, 1, 1, 1, 4, 3, 2, 4, 3, 3, 2,
       3, 2, 2, 3, 2, 4, 2, 3, 2, 1, 1, 3, 4, 2, 3, 2, 4, 3, 1, 1, 4, 4,
       1, 4, 4, 2, 4, 3, 3, 4, 4, 3, 2, 1])

In [33]:
np.random.randint(1, 5, size = (3, 3))

array([[1, 4, 2],
       [2, 3, 3],
       [4, 4, 3]])

In [34]:
simpan = np.random.randint(1, 5, size = (9, 9))
print(simpan)

[[4 2 4 1 4 1 1 4 3]
 [1 2 1 1 1 2 2 4 4]
 [4 1 1 2 2 2 1 2 4]
 [1 3 4 4 4 1 4 4 1]
 [3 2 1 2 1 3 2 3 3]
 [1 1 2 4 4 2 4 3 3]
 [3 2 4 4 4 1 2 3 1]
 [2 3 4 4 1 4 4 4 4]
 [2 2 2 3 2 3 1 4 2]]


In [37]:
simpan[0:3]

array([[4, 2, 4, 1, 4, 1, 1, 4, 3],
       [1, 2, 1, 1, 1, 2, 2, 4, 4],
       [4, 1, 1, 2, 2, 2, 1, 2, 4]])

In [40]:
simpan[:,4]

array([4, 1, 2, 4, 1, 4, 4, 1, 2])

In [43]:
data = np.array([[1, 2],
                [3, 4], 
                [5, 6]])

data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
data[0, 1]

2

In [45]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [46]:
data[0:2, 0]

array([1, 3])

In [1]:
import numpy as np
arr = np.array([[1, 2], 
                [3, 4],
                [5, 6]])

In [2]:
arr.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr.reshape((2, 5)))
print(arr.reshape((5, 2)))
print(arr.reshape((10, 1)))
print(arr.reshape((1, 10)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[ 1  2  3  4  5  6  7  8  9 10]]


In [10]:
arr.reshape((2, 5)).T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [15]:
grid = np.arange(1, 10).reshape(3, 3)
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
oneD = np.arange(1, 10).reshape(1, 9)
oneD

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [27]:
x = np.array([1, 2, 3])

print(x.reshape((1,3)))
print(x[np.newaxis, :])


print(x.reshape((3,1)))
print(x[:, np.newaxis])

[[1 2 3]]
[[1 2 3]]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


In [33]:
# Array concatination (menggabungkan array)

#1 dimension
print(np.concatenate([x, x, x, x]))

print(np.vstack([x, x]))

print(np.hstack([x, x]))

[1 2 3 1 2 3 1 2 3 1 2 3]
[[1 2 3]
 [1 2 3]]
[1 2 3 1 2 3]


In [ ]:
# Dua  dimensi : sambung pertemuan selanjutnya
